### PR TITLE
Remove outdated EPEL 9 workaround

### PR DESCRIPTION
**Pull request by nforro**
Sync of downstream change: https://src.fedoraproject.org/rpms/python-ogr/pull-request/688

### CODE REVIEW

**Comment by nforro** [comment]
Well, it seems the workaround is not so outdated after all :sweat_smile:

**Comment by nforro** [comment]
The Packit integration tests will fail until https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2024-d114d9ea20 is in `stable`.

**Review by lbarcziova — APPROVED** [review]

**Pull request merged**
