### PR TITLE
Added unit test for Pagure.PullRequest.head_commit

### PR DESCRIPTION
**Pull request by sakalosj**
Added unit test for Pagure.PullRequest.head_commit

### CODE REVIEW

**Comment by sakalosj** [comment]
based on discussion with @lachmanfrantisek not required

**Comment by TomasTomecek** [comment]
is this what we want to talk about in the arch sessions?

**Comment by lachmanfrantisek** [comment]
> is this what we want to talk about in the arch sessions?

Originally yes, but we removed that. We have some idea about this approach with @sakalosj.

- [ ] have basic flexmock structure for all instances
- [ ] have some example tests
- [ ] have it documented in the contribution guide

Then, for each new functionality, you will:
- add a test using requre
- add a unit test using approach from this PR:
  - add a dummy value to the flexmock structure
  - add a test using the flexmock structure

**Pull request closed without merging**
