### PR TITLE
Bump prepare-release version

### PR DESCRIPTION
**Pull request by FrNecas**

### CODE REVIEW

**Comment by FrNecas** [comment]
Closing in favour of #772

**Comment by nforro** [comment]
So that's why I had the feeling like this has been already done :slightly_smiling_face:

**Comment by majamassarini** [comment]
Oh, I didn't see it. I thought we forget ogr.

**Comment by FrNecas** [comment]
Haha, no problem. I got a bit surprised that one of the checks failed and then forgot to take a look into it/merge ;)

**Pull request closed without merging**
