### PR TITLE
Implemented project.exists for GitHub (#480)

### PR DESCRIPTION
**Pull request by path2himanshu**
Implemented project.exists for GitHub. #480

@lachmanfrantisek  Please review.

### CODE REVIEW

**Review by lachmanfrantisek — COMMENTED** [review]
Thanks, no objections to the code!

We only need to make CI happy:

> Requre response files cleanup............................................Failed

Can you please try [running pre-commit locally](https://github.com/packit/contributing#pre-commit)?
(One of the steps is cleanup of the requre files, you only need to run it and commit the changes. Let me know if you have any problems with that.)

**Comment by lachmanfrantisek** [comment]
```
Message: An unexpected error occurred when creating the SRPM: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-store', 'Content-Type': 'application/json', 'Date': 'Thu, 21 Jan 2021 08:03:30 GMT', 'Content-Length': '433'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"docker-io-usercont-sandcastle-stg-20210121-080330722562\" is forbidden: exceeded quota: 74746f6d6563656b407265646861742e636f6d-timebound, requested: limits.memory=768Mi, used: limits.memory=5Gi, limited: limits.memory=5Gi","reason":"Forbidden","details":{"name":"docker-io-usercont-sandcastle-stg-20210121-080330722562","kind":"pods"},"code":403}
```

Don't worry about the errors from some packit builds -- we hit some memory issues in the infrastructure.

**Comment by path2himanshu** [comment]
@lachmanfrantisek -  I've ran the pre-commit locally and updated the changes. Please trigger the CI.

**Review by mfocko — APPROVED** [review]
LGTM, thanks for your contribution :)

**Review by lachmanfrantisek — APPROVED** [review]
Thanks for your contribution!

**Comment by lachmanfrantisek** [comment]
Looks like we merged something in the meantime -- I am going to rebase myself.

**Pull request merged**
