### PR TITLE
Refactor exceptions for non-supported features,

### PR DESCRIPTION
**Pull request by bcrocker15**
Refactor exceptions for non-supported features,
changing NotImplementedError to OperationNotSupported
where a method is not supported on a particular Git forge.

Fixes ogr issue #478.

Signed-off-by: Ben Crocker <bcrocker@redhat.com>

### CODE REVIEW

**Review by lachmanfrantisek — COMMENTED** [review]
Take a look at the CI output and ideally, run the tests locally. It will show you the failed tests that needs update, e.g. here: https://softwarefactory-project.io/zuul/t/packit-service/build/3ce54a95a7cc4551909c833ca9052a94

```
=================================== FAILURES ===================================
_______________________ Issues.test_create_private_issue _______________________

self = <tests.integration.github.test_issues.Issues testMethod=test_create_private_issue>

    def test_create_private_issue(self):
        with self.assertRaises(NotImplementedError):
>           self.hello_world_project.create_issue(
                title=self.title, body=self.description, private=True
            )

self       = <tests.integration.github.test_issues.Issues testMethod=test_create_private_issue>

tests/integration/github/test_issues.py:43: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def create_issue(
        self,
        title: str,
        body: str,
        private: Optional[bool] = None,
        labels: Optional[List[str]] = None,
        assignees: Optional[List[str]] = None,
    ) -> Issue:
        if private:
>           raise OperationNotSupported("Private issues are not supported by Github")
E           ogr.exceptions.OperationNotSupported: Private issues are not supported by Github


ogr/services/github/project.py:303: OperationNotSupported
```

**Comment by mfocko** [comment]
Just fyi, there is also this document: https://github.com/packit/ogr/blob/main/COMPATIBILITY.md
I think it could be helpful :)

**Comment by csomh** [comment]
> Just fyi, there is also this document: https://github.com/packit/ogr/blob/main/COMPATIBILITY.md
> I think it could be helpful :)

@bcrocker15, based on this list the `body` setter in `services/pagure/comments.py` should also raise `OperationNotSupported`.

**Comment by csomh** [comment]
Hey @bcrocker15 what is the status of this? Do you need any help?

From the frequent actions from pre-commit.ci on this PR, I'm wondering whether you have the pre-commit hooks installed. If yes, they should run before each commit is created and fix issues if there are any.

**Comment by lachmanfrantisek** [comment]
@csomh We solved the regeneration with Ben yesterday and I asked Ben to squash the commits. So, this part should be fine, but you are right with the pre-commit -- this can be done locally and as a part of the first commit.

**Review by lachmanfrantisek — APPROVED** [review]
Good job, thanks!

**Pull request merged**
