### PR TITLE
Switch to pyproject.toml and hatchling and get rid of setuptools_scm_git_archive

### LINKED ISSUE #798: 2023 python packaging
- [x] all our projects DO NOT use setup.py and have pyproject.toml instead
  - [x] packit - packit/packit#1913 
  - [x] ogr & remove `-W ignore` introduced with this commit https://github.com/packit/ogr/pull/769/commits/f4b4a7a8130c23e375607334e22b9804e4dd9d47
  - [x] specfile - /packit/specfile#177
- [x] all our specfiles use the new pyproject-rpm-macros (`%pyproject_{wheel,install,save_*}`)
  - [x] packit
  - [x] ogr
  - [x] specfile
- [ ] all builds in packit are passing
- [ ] testing farm tests are green
- [ ] specfiles are up to date in src.fp.o

### LINKED ISSUE #805: `setuptools_scm_git_archive` is obsolete since setuptools_scm version 7
setuptools_scm version 7 and newer supports Git archives by itself. The migration guide is available in the [Readme](https://github.com/Changaco/setuptools_scm_git_archive#readme) of the project.

The problem is, that the plugin [is not compatible](https://github.com/Changaco/setuptools_scm_git_archive/issues/23) with setuptools_scm 8, and the incompatibility might break your builds.

### PR DESCRIPTION
**Pull request by nforro**
Fixes #798.
Fixes #805.

### CODE REVIEW

**Comment by nforro** [comment]
Koji builds should be fixed by https://github.com/packit/sandcastle/pull/198.

**Review by jpopelka — APPROVED** [review]

**Pull request merged**
