### PR TITLE
Authentication type: `gitlab` results in `TypeError`

### PR DESCRIPTION
**Pull request by mfocko**

### CODE REVIEW

**Review by TomasTomecek — APPROVED** [review]
This will totally solve my problem, thank you!

I'm personally not fond of this "argument eating" so if you think this is a good idea, I'm not gonna block the merge :)

I'd probably at least logger.warn about arguments which were not processed.

**Comment by mfocko** [comment]
> This will totally solve my problem, thank you!
> 
> I'm personally not fond of this "argument eating" so if you think this is a good idea, I'm not gonna block the merge :)
> 
> I'd probably at least logger.warn about arguments which were not processed.

It's done in each of the services; I still need to rebase, so if you insist I can change it before pushing :)

**Comment by TomasTomecek** [comment]
> It's done in each of the services; I still need to rebase, so if you insist I can change it before pushing :)

I approved, you're welcome to merge.

**Comment by TomasTomecek** [comment]
someone is cautious :)

**Comment by mfocko** [comment]
> someone is cautious :)

Better than debug :D

**Pull request merged**
