### PR TITLE
WIP: Tmt local run

### PR DESCRIPTION
**Pull request by lachmanfrantisek**
- Be able to run tests via tmt also locally.

### CODE REVIEW

**Comment by psss** [comment]
Please, try this config:

```yaml
/smoke:
    execute:
        script: python3 -c "import ogr"

/full:
    prepare:
        how: ansible
        playbooks: files/packit-testing-farm-prepare.yaml
    execute:
        script: make check
```

It should work both with `tmt` (latest) and `cruncher`.

**Comment by lachmanfrantisek** [comment]
We probably need to wait for tmt in testing-farm to make this work.

**Comment by psss** [comment]
Local execution including preparation using ansible should now be fully supported in `tmt`. The above-mentioned example looks good. Could you please re-test with the latest package from [copr](https://copr.fedorainfracloud.org/coprs/psss/tmt/)?

**Comment by psss** [comment]
@thrix, shall we try to fix this in cruncher? Or the time has come to (slowly but surely) replace it with tmt?

**Comment by thrix** [comment]
> @thrix, shall we try to fix this in cruncher? Or the time has come to (slowly but surely) replace it with tmt?

No we should make cruncher run tmt finally. I will try to do it this week.

**Comment by psss** [comment]
Nice. That would be great!

**Comment by lachmanfrantisek** [comment]
Let's wait for the new runner.

**Comment by lachmanfrantisek** [comment]
We are still waiting for the new TF API.

**Comment by jpopelka** [comment]
Superseded by #541

**Pull request closed without merging**
